-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:a9943001caf52dbfcb20609e2914db1f$
-- 

return {
	texture = 'interface.png',
	frames = {
			{
				name = "btn_buy.png",
				spriteColorRect = { x = 1, y = 0, width = 128, height = 35 },
				uvRect = { u0 = 0.614625, v0 = 0.223265, u1 = 0.867589, v1 = 0.288931 },
				spriteSourceSize = { width = 129, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "btn_buy_active.png",
				spriteColorRect = { x = 0, y = 0, width = 129, height = 34 },
				uvRect = { u0 = 0.614625, v0 = 0.296435, u1 = 0.869565, v1 = 0.360225 },
				spriteSourceSize = { width = 129, height = 36 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "btn_cancel_active_b.png",
				spriteColorRect = { x = 0, y = 1, width = 290, height = 34 },
				uvRect = { u0 = 0.00790514, v0 = 0.204503, u1 = 0.0750988, v1 = 0.748593 },
				spriteSourceSize = { width = 290, height = 36 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_cancel_b.png",
				spriteColorRect = { x = 1, y = 1, width = 289, height = 35 },
				uvRect = { u0 = 0.083004, v0 = 0.204503, u1 = 0.152174, v1 = 0.746717 },
				spriteSourceSize = { width = 290, height = 36 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_close.png",
				spriteColorRect = { x = 0, y = 1, width = 43, height = 44 },
				uvRect = { u0 = 0.756917, v0 = 0.718574, u1 = 0.841897, v1 = 0.801126 },
				spriteSourceSize = { width = 43, height = 45 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "btn_close_active.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 43 },
				uvRect = { u0 = 0.879447, v0 = 0.602251, u1 = 0.964427, v1 = 0.682927 },
				spriteSourceSize = { width = 43, height = 45 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "btn_facebook.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 59 },
				uvRect = { u0 = 0.618577, v0 = 0.810507, u1 = 0.735178, v1 = 0.919325 },
				spriteSourceSize = { width = 58, height = 59 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_hint_add.png",
				spriteColorRect = { x = 0, y = 0, width = 81, height = 35 },
				uvRect = { u0 = 0.918972, v0 = 0.341463, u1 = 0.988142, v1 = 0.493433 },
				spriteSourceSize = { width = 81, height = 35 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "btn_hint_add_active.png",
				spriteColorRect = { x = 0, y = 0, width = 81, height = 34 },
				uvRect = { u0 = 0.618577, v0 = 0.476548, u1 = 0.778656, v1 = 0.540338 },
				spriteSourceSize = { width = 81, height = 35 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "btn_hint_remove.png",
				spriteColorRect = { x = 0, y = 0, width = 81, height = 35 },
				uvRect = { u0 = 0.391304, v0 = 0.893058, u1 = 0.551383, v1 = 0.958724 },
				spriteSourceSize = { width = 81, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "btn_hint_remove_active.png",
				spriteColorRect = { x = 0, y = 0, width = 81, height = 34 },
				uvRect = { u0 = 0.543478, v0 = 0.733584, u1 = 0.610672, v1 = 0.885553 },
				spriteSourceSize = { width = 81, height = 35 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_hint_skip.png",
				spriteColorRect = { x = 0, y = 0, width = 81, height = 35 },
				uvRect = { u0 = 0.391304, v0 = 0.733584, u1 = 0.460474, v1 = 0.885553 },
				spriteSourceSize = { width = 81, height = 35 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "btn_hint_skip_active.png",
				spriteColorRect = { x = 0, y = 0, width = 81, height = 34 },
				uvRect = { u0 = 0.468379, v0 = 0.733584, u1 = 0.535573, v1 = 0.885553 },
				spriteSourceSize = { width = 81, height = 35 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_letter_active_b.png",
				spriteColorRect = { x = 4, y = 0, width = 32, height = 44 },
				uvRect = { u0 = 0.618577, v0 = 0.926829, u1 = 0.705534, v1 = 0.986867 },
				spriteSourceSize = { width = 40, height = 46 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_letter_b.png",
				spriteColorRect = { x = 4, y = 0, width = 33, height = 44 },
				uvRect = { u0 = 0.909091, v0 = 0.500938, u1 = 0.974308, v1 = 0.58349 },
				spriteSourceSize = { width = 40, height = 46 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "btn_next.png",
				spriteColorRect = { x = 0, y = 0, width = 89, height = 35 },
				uvRect = { u0 = 0.00790514, v0 = 0.756098, u1 = 0.0770751, v1 = 0.923077 },
				spriteSourceSize = { width = 89, height = 35 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_next_active.png",
				spriteColorRect = { x = 0, y = 0, width = 89, height = 34 },
				uvRect = { u0 = 0.0849802, v0 = 0.754221, u1 = 0.152174, v1 = 0.921201 },
				spriteSourceSize = { width = 89, height = 35 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_next_tutorial.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 34 },
				uvRect = { u0 = 0.614625, v0 = 0.15197, u1 = 0.871542, v1 = 0.21576 },
				spriteSourceSize = { width = 130, height = 34 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "btn_next_tutorial_active.png",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 34 },
				uvRect = { u0 = 0.0849802, v0 = 0.928705, u1 = 0.341897, v1 = 0.992495 },
				spriteSourceSize = { width = 130, height = 34 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "btn_share.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 34 },
				uvRect = { u0 = 0.802372, v0 = 0.926829, u1 = 0.865613, v1 = 0.990619 },
				spriteSourceSize = { width = 32, height = 34 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "btn_share_active.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 34 },
				uvRect = { u0 = 0.91502, v0 = 0.0806754, u1 = 0.978261, v1 = 0.144465 },
				spriteSourceSize = { width = 32, height = 34 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "btn_share_cancel.png",
				spriteColorRect = { x = 0, y = 0, width = 278, height = 47 },
				uvRect = { u0 = 0.00790514, v0 = 0.108818, u1 = 0.557312, v1 = 0.196998 },
				spriteSourceSize = { width = 278, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "btn_skip_tutorial.png",
				spriteColorRect = { x = 0, y = 0, width = 131, height = 34 },
				uvRect = { u0 = 0.539526, v0 = 0.204503, u1 = 0.606719, v1 = 0.450281 },
				spriteSourceSize = { width = 131, height = 34 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_skip_tutorial_active.png",
				spriteColorRect = { x = 0, y = 0, width = 131, height = 34 },
				uvRect = { u0 = 0.648221, v0 = 0.0806754, u1 = 0.907115, v1 = 0.144465 },
				spriteSourceSize = { width = 131, height = 34 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "btn_sms.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 59 },
				uvRect = { u0 = 0.87747, v0 = 0.223265, u1 = 0.992095, v1 = 0.333959 },
				spriteSourceSize = { width = 58, height = 59 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "btn_sound_off.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 54 },
				uvRect = { u0 = 0.27668, v0 = 0.752345, u1 = 0.383399, v1 = 0.917448 },
				spriteSourceSize = { width = 89, height = 56 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_sound_on.png",
				spriteColorRect = { x = 0, y = 0, width = 89, height = 55 },
				uvRect = { u0 = 0.160079, v0 = 0.752345, u1 = 0.268775, v1 = 0.919325 },
				spriteSourceSize = { width = 89, height = 56 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_start.png",
				spriteColorRect = { x = 0, y = 0, width = 164, height = 35 },
				uvRect = { u0 = 0.648221, v0 = 0.00750469, u1 = 0.972332, v1 = 0.0731707 },
				spriteSourceSize = { width = 164, height = 35 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "btn_start_active.png",
				spriteColorRect = { x = 0, y = 0, width = 164, height = 34 },
				uvRect = { u0 = 0.464427, v0 = 0.204503, u1 = 0.531621, v1 = 0.512195 },
				spriteSourceSize = { width = 164, height = 35 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_twitter.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 59 },
				uvRect = { u0 = 0.482213, v0 = 0.617261, u1 = 0.598814, v1 = 0.726079 },
				spriteSourceSize = { width = 58, height = 59 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "btn_vkontakte.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 59 },
				uvRect = { u0 = 0.796443, v0 = 0.36773, u1 = 0.911067, v1 = 0.478424 },
				spriteSourceSize = { width = 58, height = 59 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 31 },
				uvRect = { u0 = 0.713439, v0 = 0.926829, u1 = 0.794466, v1 = 0.984991 },
				spriteSourceSize = { width = 41, height = 31 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "coin_icon.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 19 },
				uvRect = { u0 = 0.565217, v0 = 0.108818, u1 = 0.602767, v1 = 0.144465 },
				spriteSourceSize = { width = 19, height = 19 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "coin_shadow.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 40 },
				uvRect = { u0 = 0.464427, v0 = 0.5197, u1 = 0.543478, v1 = 0.609756 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "dot.png",
				spriteColorRect = { x = 3, y = 3, width = 9, height = 9 },
				uvRect = { u0 = 0.87747, v0 = 0.341463, u1 = 0.895257, v1 = 0.358349 },
				spriteSourceSize = { width = 16, height = 16 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "dot_active.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 15 },
				uvRect = { u0 = 0.610672, v0 = 0.108818, u1 = 0.640316, v1 = 0.136961 },
				spriteSourceSize = { width = 16, height = 16 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "empty_pixel.png",
				spriteColorRect = { x = 0, y = 0, width = 8, height = 8 },
				uvRect = { u0 = 0.952569, v0 = 0.15197, u1 = 0.968379, v1 = 0.166979 },
				spriteSourceSize = { width = 8, height = 8 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "icon_4pics.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 58 },
				uvRect = { u0 = 0.865613, v0 = 0.801126, u1 = 0.980237, v1 = 0.909944 },
				spriteSourceSize = { width = 58, height = 58 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icon_emoji.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 58 },
				uvRect = { u0 = 0.756917, v0 = 0.602251, u1 = 0.871542, v1 = 0.711069 },
				spriteSourceSize = { width = 58, height = 58 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icon_fb.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 66 },
				uvRect = { u0 = 0.618577, v0 = 0.679174, u1 = 0.749012, v1 = 0.803002 },
				spriteSourceSize = { width = 66, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "icon_mail.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 66 },
				uvRect = { u0 = 0.606719, v0 = 0.547842, u1 = 0.737154, v1 = 0.67167 },
				spriteSourceSize = { width = 66, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "icon_puzzle.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 58 },
				uvRect = { u0 = 0.743083, v0 = 0.810507, u1 = 0.857708, v1 = 0.919325 },
				spriteSourceSize = { width = 58, height = 58 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icon_scratch.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 58 },
				uvRect = { u0 = 0.786561, v0 = 0.485929, u1 = 0.901186, v1 = 0.594747 },
				spriteSourceSize = { width = 58, height = 58 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "icon_tweet.png",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 66 },
				uvRect = { u0 = 0.160079, v0 = 0.621013, u1 = 0.290514, v1 = 0.744841 },
				spriteSourceSize = { width = 66, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "letter_bg.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 31 },
				uvRect = { u0 = 0.559289, v0 = 0.893058, u1 = 0.610672, v1 = 0.951219 },
				spriteSourceSize = { width = 26, height = 31 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "options_btn.png",
				spriteColorRect = { x = 0, y = 0, width = 89, height = 55 },
				uvRect = { u0 = 0.298419, v0 = 0.622889, u1 = 0.474308, v1 = 0.726079 },
				spriteSourceSize = { width = 89, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "options_btn_active.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 54 },
				uvRect = { u0 = 0.614625, v0 = 0.36773, u1 = 0.788538, v1 = 0.469043 },
				spriteSourceSize = { width = 89, height = 56 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "options_icon.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 28 },
				uvRect = { u0 = 0.539526, v0 = 0.457786, u1 = 0.602767, v1 = 0.510319 },
				spriteSourceSize = { width = 32, height = 28 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "orange_bg.png",
				spriteColorRect = { x = 0, y = 0, width = 1, height = 1 },
				uvRect = { u0 = 0.786561, v0 = 0.476548, u1 = 0.788538, v1 = 0.478424 },
				spriteSourceSize = { width = 1, height = 1 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "restart_btn.png",
				spriteColorRect = { x = 1, y = 0, width = 218, height = 35 },
				uvRect = { u0 = 0.237154, v0 = 0.204503, u1 = 0.306324, v1 = 0.613508 },
				spriteSourceSize = { width = 219, height = 35 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "restart_btn_active.png",
				spriteColorRect = { x = 0, y = 0, width = 219, height = 34 },
				uvRect = { u0 = 0.389328, v0 = 0.204503, u1 = 0.456522, v1 = 0.615385 },
				spriteSourceSize = { width = 219, height = 35 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "set_lang_btn.png",
				spriteColorRect = { x = 1, y = 0, width = 218, height = 35 },
				uvRect = { u0 = 0.160079, v0 = 0.204503, u1 = 0.229249, v1 = 0.613508 },
				spriteSourceSize = { width = 219, height = 35 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "set_lang_btn_active.png",
				spriteColorRect = { x = 0, y = 0, width = 219, height = 34 },
				uvRect = { u0 = 0.314229, v0 = 0.204503, u1 = 0.381423, v1 = 0.615385 },
				spriteSourceSize = { width = 219, height = 35 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "shop_icon1.png",
				spriteColorRect = { x = 4, y = 1, width = 32, height = 33 },
				uvRect = { u0 = 0.922925, v0 = 0.690432, u1 = 0.986166, v1 = 0.752345 },
				spriteSourceSize = { width = 40, height = 34 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "shop_icon2.png",
				spriteColorRect = { x = 3, y = 0, width = 33, height = 34 },
				uvRect = { u0 = 0.879447, v0 = 0.15197, u1 = 0.944664, v1 = 0.21576 },
				spriteSourceSize = { width = 40, height = 34 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "shop_icon3.png",
				spriteColorRect = { x = 3, y = 0, width = 33, height = 33 },
				uvRect = { u0 = 0.873518, v0 = 0.917448, u1 = 0.938735, v1 = 0.979362 },
				spriteSourceSize = { width = 40, height = 34 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "shop_icon4.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 33 },
				uvRect = { u0 = 0.849802, v0 = 0.718574, u1 = 0.91502, v1 = 0.793621 },
				spriteSourceSize = { width = 40, height = 34 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "shop_icon5.png",
				spriteColorRect = { x = 3, y = 0, width = 33, height = 34 },
				uvRect = { u0 = 0.00790514, v0 = 0.930582, u1 = 0.0750988, v1 = 0.992495 },
				spriteSourceSize = { width = 40, height = 34 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "top_bg.png",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 50 },
				uvRect = { u0 = 0.00790514, v0 = 0.00750469, u1 = 0.640316, v1 = 0.101313 },
				spriteSourceSize = { width = 320, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

