-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:55b92691722a792ecffc583a5e8bac22$
-- 

return {
	texture = 'bg.png',
	frames = {
			{
				name = "finish_iphone5.png",
				spriteColorRect = { x = 0, y = 0, width = 640, height = 1136 },
				uvRect = { u0 = 0.500778, v0 = 0.00175439, u1 = 0.998445, v1 = 0.998246 },
				spriteSourceSize = { width = 640, height = 1136 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "game_bg_iphone5.png",
				spriteColorRect = { x = 0, y = 0, width = 640, height = 1136 },
				uvRect = { u0 = 0.00155521, v0 = 0.00175439, u1 = 0.499222, v1 = 0.998246 },
				spriteSourceSize = { width = 640, height = 1136 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

