-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:1e2f2915a17745e2972d6f826ff1153d$
-- 

return {
	texture = 'bg.png',
	frames = {
			{
				name = "finish_iphone5.png",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 568 },
				uvRect = { u0 = 0.501548, v0 = 0.0034965, u1 = 0.996904, v1 = 0.996503 },
				spriteSourceSize = { width = 320, height = 568 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "game_bg_iphone5.png",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 568 },
				uvRect = { u0 = 0.00309598, v0 = 0.0034965, u1 = 0.498452, v1 = 0.996503 },
				spriteSourceSize = { width = 320, height = 568 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

