-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:107c2b98803b47103b9b0ab047c1deaa:1/1$
-- 

return {
	texture = 'nine.png',
	frames = {
			{
				name = "button_normal.9.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 48 },
				uvRect = { u0 = 0.440678, v0 = 0.015625, u1 = 0.847458, v1 = 0.390625 },
				spriteSourceSize = { width = 48, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "button_selected.9.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 48 },
				uvRect = { u0 = 0.0169492, v0 = 0.015625, u1 = 0.423729, v1 = 0.390625 },
				spriteSourceSize = { width = 48, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "listitem_background.9.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.711864, v0 = 0.671875, u1 = 0.983051, v1 = 0.921875 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "panel.9.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.711864, v0 = 0.40625, u1 = 0.983051, v1 = 0.65625 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "slider_background.9.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 30 },
				uvRect = { u0 = 0.0169492, v0 = 0.75, u1 = 0.220339, v1 = 0.984375 },
				spriteSourceSize = { width = 24, height = 38 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "slider_progress.9.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 30 },
				uvRect = { u0 = 0.237288, v0 = 0.75, u1 = 0.423729, v1 = 0.984375 },
				spriteSourceSize = { width = 24, height = 38 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "textinput_normal.9.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 42 },
				uvRect = { u0 = 0.0169492, v0 = 0.40625, u1 = 0.694915, v1 = 0.734375 },
				spriteSourceSize = { width = 80, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

